using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestUtil
{
    /// <summary>
    /// Represents an Asset, generated by a script 
    /// </summary>
    public class AssetRecord:BaseRecord
    {
        internal AssetRecord(BaseRecord baseRecord)
            : base(baseRecord)
        {
            Data = string.Empty;
            DataNative = null;
        }

        /// <summary>
        /// Data of this asset
        /// </summary>
        public string Data { get; internal set; }

        /// <summary>
        /// Real object data behind the data
        /// </summary>
        internal object DataNative { get; set; }
        
        /// <summary>
        /// TRUE if DataNative does point to something useful
        /// </summary>
        internal bool IsDataNativeSet
        {
            get
            {
                return (DataNative != null);
            }
        }


        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("Value: ").Append(Data).Append("; ").Append(base.ToString());
            return sb.ToString();
        }
        
    }
}
