using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TestUtil;
using Yamua;

namespace TestUtilOutputGenerator_Consumer
{
    class TestUtilOutputGeneratorConsumerProgram
    {
        static void Main(string[] args)
        {
            TestUtilRunner runner = new TestUtilRunner();

            string basepath = "";
            //basepath = DebugOnlyHelper.DebugOnlyScriptFolderHelper.TestingScriptDirectory();

            basepath = @"C:\dev\gitrepos\testutil\src\ScriptsForTesting\Test1";
            //basepath = @"C:\dev\gitrepos\testutil\scripts";


            Task<Report> task = RunEngineAsync(runner, basepath);

            bool finished = false;
            while (finished == false)
            {
                Console.WriteLine("Waiting for runner to finish...");
                finished = task.Wait(333);
            }

            Report report = task.Result;

            //Set a text on this report
            report.UserText = "Generated by debug consumer";

            string templateFile = basepath + @"\BootstrapTemplate1.html";

            BootstrapHTMLGenerator generator = new BootstrapHTMLGenerator(templateFile);
            //string html = generator.Generate(report);
            string tempFile = generator.GenerateAndSaveFile(report);

            Process.Start(tempFile);
            

            //Console.WriteLine("Press return to exit...");
            //Console.ReadLine();
        }


        //This function allows use to use await - see http://blogs.msdn.com/b/pfxteam/archive/2012/04/12/10293335.aspx
        private static async Task<Report> RunEngineAsync(TestUtilRunner Runner, string BasePath)
        {
            Report result;
            result = await Runner.RunAsync(BasePath);
            Console.WriteLine("Async finished!");
            return result;
        }
    }
}
